### ISSUE TITLE
Footer design

### ISSUE THREAD

**Issue by harshitpdoshi** [ijenghadiya/preset-website#5]
Design a footer.

What should the footer contain?

Assign this issue to me, @ijenghadiya .

**Comment by ijenghadiya** [comment]
For now, it should only contain the year and copyright information

**Comment by harshitpdoshi** [comment]
Okay, thanks!

**Comment by harshitpdoshi** [comment]
Closing this issue as the design has been added in the form of a DTL file in the main project repo containing the Django app.
